### ISSUE TITLE
ImportError: cannot import name 'Buffer' from 'collections.abc'

### ISSUE THREAD

**Issue by ElytroYT** [ego-lay-atman-bay/luna-kit#9]
When I tried to run this command: luna-kit dump "ark files/*.ark" -o "extracted", I got this error: 
<img width="1288" height="267" alt="Image" src="https://github.com/user-attachments/assets/79db590e-4f94-407f-9116-91a352310b86" />

And this is what is in the file the error refers to
<img width="580" height="233" alt="Image" src="https://github.com/user-attachments/assets/53504b78-109b-4e7e-ab6c-6edf4b94e46f" />

**Comment by ego-lay-atman-bay** [comment]
Thanks for the report, will fix as soon as I can. In the meantime you should be able to just update python to the latest version and the issue with go away (it's just something that was introduced in python 3.12, but I will make sure it works in 3.11).

**Comment by ElytroYT** [comment]
Thanks for the help, updating python worked

**Comment by ego-lay-atman-bay** [comment]
Alright, this should be solved now
